### ISSUE TITLE
How to fix?

### ISSUE THREAD

**Issue by eClipZe88** [s4n7h0/NSE#2]
sudo nmap --script-updatedb

Starting Nmap 7.50 ( https://nmap.org ) at 2017-07-12 21:07 CEST
NSE: Updating rule database.
NSE: Failed to load /usr/bin/../share/nmap/scripts//http-lfi.nse:
/usr/bin/../share/nmap/scripts//http-lfi.nse:37: variable 'shortport' is not declared
stack traceback:
	[C]: in function 'error'
	/usr/bin/../share/nmap/nselib/strict.lua:80: in metamethod '__index'
	/usr/bin/../share/nmap/scripts//http-lfi.nse:37: in function </usr/bin/../share/nmap/scripts//http-lfi.nse:1>
NSE: failed to initialize the script engine:
/usr/bin/../share/nmap/nse_main.lua:619: could not load script
stack traceback:
	[C]: in function 'error'
	/usr/bin/../share/nmap/nse_main.lua:619: in field 'new'
	/usr/bin/../share/nmap/nse_main.lua:1296: in main chunk
	[C]: in ?

QUITTING!

Any idea how to fix?

**Comment by s4n7h0** [comment]
The old version would not needed a variable declaration. Changes are made now. 
Thanks for pointing out.
